### ISSUE TITLE
Create and publish standardized Docker image for all gateway services

### ISSUE THREAD

**Issue by JoeCap08055** [AmplicaLabs/social-app-template#6]
# Description
As a user, I want to have a standard, published Docker image for each Gateway backend service. Each Docker image should be configured suitably for production deployment. Each repo should include a CI release pipeline for tagging & publishing a new Docker image upon a repository release tag.

- [ ] AmplicaLabs/graph-service#52
- [ ] AmplicaLabs/account-service#25
- [ ] AmplicaLabs/content-publishing-service#88
- [ ] AmplicaLabs/content-watcher-service#31
